version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - autoincrement
  - biomejs
  - datasource
  - healthcheck
  - hono
  - mydb
  - mysqladmin
  - openapi
ignoreWords: []
import: []
