version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - autoincrement
  - biomejs
  - datasource
  - fabbrica
  - healthcheck
  - hono
  - mydb
  - mysqladmin
  - openapi
  - quramy
ignoreWords: []
import: []
